---
title: "Traversal"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(pracma)
library(SimilarityMeasures)
library(swaRm)
```

## R Markdown

```{r}
#scardat <- read.csv("Scars/3New-02.csv")
#ggplot(scardat, aes(x = x, y = y)) + geom_point()
```

```{r pressure}
dat <- read_lines("3New-02.txt") #5-01-2021 (14) #Circular2 #BotsonNeuron2
indices <- which(str_detect(dat, "Line"))
centreline <- data.frame(col1 = dat[indices[1]:(indices[2]-1)])
lowerline <- data.frame(col1 = dat[indices[2]:(indices[3]-1)])
upperline <- data.frame(col1 = dat[indices[3]:(indices[4]-1)])
met2 <- data.frame(col1 = dat[indices[4]:(indices[5]-1)])
met3 <- data.frame(col1 = dat[indices[5]:length(dat)])
```


```{r pressure}
upper2num <- matrix(as.numeric(str_extract_all(upperline, "(-)?[0-9]+(\\.[0-9]+)?")[[1]]), ncol = 2, byrow = TRUE)
lower2num <- matrix(as.numeric(str_extract_all(lowerline, "(-)?[0-9]+(\\.[0-9]+)?")[[1]]), ncol = 2, byrow = TRUE)
centre2num <- matrix(as.numeric(str_extract_all(centreline, "(-)?[0-9]+(\\.[0-9]+)?")[[1]]), ncol = 2, byrow = TRUE)
met2num <- matrix(as.numeric(str_extract_all(met2, "(-)?[0-9]+(\\.[0-9]+)?")[[1]]), ncol = 2, byrow = TRUE)
met3num <- matrix(as.numeric(str_extract_all(met3, "(-)?[0-9]+(\\.[0-9]+)?")[[1]]), ncol = 2, byrow = TRUE)
```

```{r pressure}
full <- bind_rows(as.data.frame(centre2num),as.data.frame(met2num),as.data.frame(met3num), as.data.frame(lower2num), as.data.frame(upper2num))
full$Type <- c(rep("centre",nrow(centre2num)),rep("Met2",nrow(met2num)),rep("Met3",nrow(met3num)), rep("Lower",nrow(lower2num)), rep("upper",nrow(upper2num)))
ggplot(full, aes(x = V1, y = V2)) + geom_point(aes(colour = Type))
```



```{r pressure}
keyval <- 600
met2numup <- filter(as.data.frame(met2num), V2>keyval)
met2numlow <- filter(as.data.frame(met2num), V2<keyval)
met3numup <- filter(as.data.frame(met3num), V2>keyval)
met3numlow <- filter(as.data.frame(met3num), V2<keyval)
```

```{r pressure}
full <- bind_rows(as.data.frame(met2numup),as.data.frame(met2numlow))
full$Type <- c(rep("Up",nrow(met2numup)),rep("Low",nrow(met2numlow)))
ggplot(full, aes(x = V1, y = V2)) + geom_point(aes(colour = Type))
```

```{r pressure}
lowerdf <- as.data.frame(lower2num)
botdf <- as.data.frame(centre2num)
upperdf <- as.data.frame(upper2num)
met2numlow
met2numup
met3numlow
met3numup
upperdf
lowerdf
botdf
```

```{r pressure}
#intersect_range <- purrr::reduce(list(A, B, C, D, E), inner_join, by = x)
low1 <- cor.test(heading(lowerdf$V1, lowerdf$V2), heading(botdf$V1, botdf$V2))$estimate
up1 <- cor.test(heading(upperdf$V1, upperdf$V2), heading(botdf$V1, botdf$V2))$estimate
#up2 <- cor.test(heading(met2numup[,1], met2numup[,2]), heading(centre2num[,1], centre2num[,2]))$estimate
#low2 <- cor.test(heading(met2numlow[,1], met2numlow[,2]), heading(centre2num[,1], centre2num[,2]))$estimate
#up3 <- cor.test(heading(met3numup[,1], met3numup[,2]), heading(centre2num[,1], centre2num[,2]))$estimate
#low3 <- cor.test(heading(met3numlow[,1], met3numlow[,2]), heading(centre2num[,1], centre2num[,2]))$estimate
c(up1,low1)
```

```{r pressure}
lowerdf <- as.data.frame(lower2num)
botdf <- as.data.frame(centre2num)
#intersect_range <- purrr::reduce(list(A, B, C, D, E), inner_join, by = x)
low1 <- cor.test(heading(lower2num[,1], lower2num[,2]), heading(centre2num[,1], centre2num[,2]))$estimate
up1 <- cor.test(heading(upper2num[,1], upper2num[,2]), heading(centre2num[,1], centre2num[,2]))$estimate
#up2 <- cor.test(heading(met2numup[,1], met2numup[,2]), heading(centre2num[,1], centre2num[,2]))$estimate
#low2 <- cor.test(heading(met2numlow[,1], met2numlow[,2]), heading(centre2num[,1], centre2num[,2]))$estimate
#up3 <- cor.test(heading(met3numup[,1], met3numup[,2]), heading(centre2num[,1], centre2num[,2]))$estimate
#low3 <- cor.test(heading(met3numlow[,1], met3numlow[,2]), heading(centre2num[,1], centre2num[,2]))$estimate
c(up1,low1)
```


```{r pressure}
c(DTW(met2num, upper2num), DTW(met2num, lower2num), DTW(met3num, upper2num), DTW(met3num, lower2num), DTW(centre2num, upper2num), DTW(centre2num, lower2num))
```

```{r pressure}
library(sf)
val <- st_linestring(upper2num)
plot(val)
endp <- st_coordinates(val)[c(1,nrow(upper2num)),]
upp <- as.matrix(dist(endp))[1,2]/st_length(val)
val2 <- st_linestring(lower2num)
endp2 <- st_coordinates(val2)[c(1,nrow(lower2num)),]
low <- as.matrix(dist(endp2))[1,2]/st_length(val2)
low+upp
```

```{r pressure}
u <- diag(pdist2(as.matrix(centre), as.matrix(upper)))
l <- diag(pdist2(as.matrix(upper), as.matrix(lower)))
res <- ((u-l)>=0)
reslow <- c(1:(length(l)-1))[res[-nrow(centremat)-1]]
resup <- c(1:(length(u)-1))[!(res[-nrow(centremat)-1])]
reslow
resup
lows <- lowermat[reslow,]
coslow <- vector(length = length(reslow))
cosup <- vector(length = length(resup))
ups <- uppermat[resup,]
for(i in 1:length(reslow)){
  ll <- as.numeric(lows[i,])
  cc <- as.numeric(centremat[reslow[i],])
  coslow[i] <- dot(ll,cc)/(Norm(ll)*Norm(cc))
}
for(i in 1:length(resup)){
  ll <- as.numeric(ups[i,])
  cc <- as.numeric(centremat[resup[i],])
  cosup[i] <- dot(ll,cc)/(Norm(ll)*Norm(cc))
}
c(cosup,coslow)
sum(c(cosup,coslow), na.rm = TRUE)/length(c(cosup,coslow))
```


```{r pressure}
Linear1 = 0.791835985493616 #0.55
Circular1 = 0.923346683392492 
Circular2 = 0.767648244940919 #0.65
Linear2 = 0.826748551614647 #0.4
```

```{r pressure}
results <- data.frame(rot = c(0.55, 0.4, 0.65), index = c(0.791835985493616,0.826748551614647, 0.76764824494091), typemov = c("Lin", "Lin", "Cir"))
ggplot(results, aes(x = rot, y = index)) + geom_point(aes(colour = typemov))
```

```{r pressure}
uppermat <- upper2num[-1,] - upper2num[-nrow(upper2num),]
lowermat <- lower2num[-1,] - lower2num[-nrow(lower2num),]
centremat <- centre2num[-1,] - centre2num[-nrow(centre2num),]
met2mat <- met2num[-1,] - met2num[-nrow(met2num),]
met3mat <- met3num[-1,] - met3num[-nrow(met3num),]
head(centremat)
head(met3mat)
```

```{r pressure}
summary(lm(upper2num[,2] ~ upper2num[,1]))$r.squared+summary(lm(lower2num[,2] ~ lower2num[,1]))$r.squared
```

```{r pressure}
evens <- function(x) subset(x, x %% 2 == 0)
odds <- function(x) subset(x, x %% 2 == 1)
evens(1:nrow(met2num))
odds(1:nrow(met2num))
```

```{r pressure}
full <- bind_rows(as.data.frame(centre2num),as.data.frame(met2num[evens(1:nrow(met2num)),]),as.data.frame(met2num[odds(1:nrow(met2num)),]))
full$Type <- c(rep("centre",nrow(centre2num)),rep("lower",length(evens(1:nrow(met2num)))),rep("centre1",length(odds(1:nrow(met2num)))))
ggplot(full, aes(x = V1, y = V2)) + geom_point(aes(colour = Type))
```

```{r pressure}
full <- bind_rows(as.data.frame(upper2num),as.data.frame(lower2num),as.data.frame(centre2num),as.data.frame(met2num),as.data.frame(met3num))
full$Type <- c(rep("upper",nrow(upper2num)),rep("lower",nrow(lower2num)),rep("centre1",nrow(centre2num)), rep("centre2",nrow(met2num)), rep("centre3",nrow(met3num)))
ggplot(full, aes(x = V1, y = V2)) + geom_point(aes(colour = Type))
```




