---
title: "R Notebook"
output: 
  html_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
---

---

# . Environment

```{r include=FALSE}
options(java.parameters = c("-XX:+UseConcMarkSweepGC", "-Xmx8192m"))
gc()

library(data.table)
if (!require(RBioFormats)) {
  BiocManager::install("aoles/RBioFormats")
  library(RBioFormats)
}
if (!require(Rvision)) {
  remotes::install_github("swarm-lab/Rvision")
  library(Rvision)
}
library(ggplot2)
library(ggdist)
if (!require(swaRm)) {
  remotes::install_github("swarm-lab/swaRm")
  library(swaRm)
}
if (!require(mlisi)) {
  remotes::install_github("mattelisi/mlisi")
  library(mlisi)
}
```

---

# . Data 

```{r}
rep_name <- list.files("videos/scar_traversal", include.dirs = FALSE)
rep_name <- rep_name[!grepl("dismiss", rep_name)] 
dat <- list()

for (i in 1:length(rep_name)) {
  gc()
  J("java.lang.Runtime")$getRuntime()$gc()
  
  raw <- read.image(paste0("videos/scar_traversal/", rep_name[i], "/raw.czi"))
  load(paste0("videos/scar_traversal/", rep_name[i], "/bots.rda"))
  dat[[rep_name[i]]] <- list(
    dims = dim(raw)[1:2],
    dt = raw@metadata$globalMetadata$`Experiment|AcquisitionBlock|TimeSeriesSetup|Interval|TimeSpan|Value`,
    start = as.POSIXct(raw@metadata$globalMetadata$`Information|Image|AcquisitionDateAndTime`),
    scale = raw@metadata$globalMetadata$`Scaling|Distance|Value #1`,
    scar = fread(paste0("videos/scar_traversal/", rep_name[i], "/scar.csv")),
    bot = bots
  )
  rm(raw, bots)
}
```

```{r}
for (i in 1:length(dat)) {
  scar <- zeros(dat[[i]]$dims[1], dat[[i]]$dims[2], 1)
  fillPoly(scar, dat[[i]]$scar[, 2:3])
  dat[[i]]$bot$summ <- data.table(
    rep_name = names(dat)[i],
    time = (1:length(dat[[i]]$bot) - 1) * as.numeric(dat[[i]]$dt) + dat[[i]]$start,
    x = as.numeric(NA), 
    y = as.numeric(NA), 
    h = as.numeric(NA), 
    area = as.numeric(NA),
    cov = as.numeric(NA)
  )
  
  for (j in 1:length(dat[[i]]$bot)) {
    if (!is.null(dat[[i]]$bot[[j]]$contour)) {
      dat[[i]]$bot$summ$x[j] <- dat[[i]]$bot[[j]]$centroid[1] * as.numeric(dat[[i]]$scale)
      dat[[i]]$bot$summ$y[j] <- dat[[i]]$bot[[j]]$centroid[2] * as.numeric(dat[[i]]$scale)
      
      if (dat[[i]]$bot[[j]]$valid)
        dat[[i]]$bot$summ$h[j] <- dat[[i]]$bot[[j]]$heading
      
      tmp <- zeros(dat[[i]]$dims[1], dat[[i]]$dims[2], 1)
      fillPoly(tmp, dat[[i]]$bot[[j]]$contour[, 2:3])
      dat[[i]]$bot$summ$area[j] <- (sum(tmp) / 255) * as.numeric(dat[[i]]$scale)
      dat[[i]]$bot$summ$cov[j] <- sum(tmp - scar) / sum(tmp)
    }
  }
}

summ <- rbindlist(lapply(dat, function(x) x$bot$summ))
```

---

# . Graphs

## . Coverage 

```{r}
library(tidyverse)
ggplot(na.omit(summ)[cov > 0]) +
  aes(fct_reorder(rep_name, cov), cov) + 
  stat_halfeye(width = 0.5) +
  stat_dots(side = "left", justification = 1.1, width = 0.75) +
  labs(x = NULL, y = NULL, title = "Proportion of bot on tissue") +
  theme_light(base_size = 16) +
  theme(axis.text.x = element_text(angle = 30, hjust = 1, size = 5))
```

## . Velocity

```{r}
summ[, v := linSpeed(x, y, time) * 1000000, by = .(rep_name)]

ggplot(na.omit(summ)[cov > 0]) +
  aes(fct_reorder(rep_name, v), v) + 
  stat_halfeye(width = 0.5) +
  stat_dots(side = "left", justification = 1.1, width = 0.75) +
  labs(x = NULL, y = NULL, title = expression("Instantaneous velocity"~"["*mu*m/s*"]")) +
  theme_light(base_size = 16) +
  theme(axis.text.x = element_text(angle = 30, hjust = 1, size = 5))
```

## . Angular velocity

```{r}
summ[, hv := angSpeed(x, y, time), by = .(rep_name)]

ggplot(na.omit(summ)[cov > 0]) +
  aes(fct_reorder(rep_name, abs(hv)), abs(hv)) + 
  stat_halfeye(width = 0.5) +
  stat_dots(side = "left", justification = 1.1, width = 0.75) +
  labs(x = NULL, y = NULL, title = expression("Instantaneous absolute angular velocity"~"["*rad/s*"]")) +
  theme_light(base_size = 16) +
  theme(axis.text.x = element_text(angle = 30, hjust = 1, size = 5))
```

## . Rotational tendency

```{r}
summ[, rt := c(NA, sign(hv[1:(.N-1)]) == sign(hv[2:.N])), by = .(rep_name)]
na.omit(summ)[cov > 0, list(prop = sum(rt) / .N,
                            n = .N,
                              lo = binom.test(sum(rt), .N)$conf.int[1],
                              up =  binom.test(sum(rt), .N)$conf.int[2]), 
                by = .(rep_name)] %>% arrange(prop)
na.omit(summ)[cov > 0, list(vs = sum(v) / .N, by = .(rep_name))]

ggplot(
  na.omit(summ)[cov > 0, list(prop = mean(rt), #sum(rt) / .N
                              lo = binom.test(sum(rt), .N)$conf.int[1],
                              up =  binom.test(sum(rt), .N)$conf.int[2]), 
                by = .(rep_name)]) +
  aes(fct_reorder(rep_name, prop), prop, ymin = lo, ymax = up) + 
  geom_bar(stat = "identity", width = .5) +
  geom_errorbar(width = .2) + 
  geom_hline(yintercept = 0.5, linetype = 2) +
  ylim(0, 1) +
  labs(x = NULL, y = NULL, title = expression("Rotational tendency")) +
  theme_light(base_size = 16) +
  theme(axis.text.x = element_text(angle = 30, hjust = 1, size = 5))
```

## . Velocity vs coverage

```{r}
library(plotrix)
getsem <- function(var, n, conf){
  rep <- binom.test(sum(var), n, conf.level = conf)
  lo <- rep$conf.int[1]
  hi <- rep$conf.int[2]
  es <- rep$estimate
  sterr <- (hi-es)/sqrt(n)
  reallo <- es-sterr
  realhi <- es+sterr
  return(c(reallo, realhi))
}
summsumm <- na.omit(summ)[cov > 0, 
                          list(
                            cov = mean(cov),
                            cov_lo = mean(cov)-std.error(cov), #bootMeanCI(cov)[1]
                            cov_up = mean(cov)+std.error(cov),#bootMeanCI(cov)[2]
                            v = mean(v),
                            v_lo = mean(v)-std.error(v),#bootMeanCI(v)[1],
                            v_up = mean(v)+std.error(v), #bootMeanCI(v)[2],
                            hv = mean(hv),
                            hv_lo = mean(hv)-std.error(hv),
                            hv_up = mean(hv)+std.error(hv), 
                            rt = sum(rt) / .N, 
                            rt_lo = getsem(rt,.N,0.68)[1],
                            rt_up1 = binom.test(sum(rt), .N, conf.level = 0.95)$conf.int[2],
                            rt_up = getsem(rt,.N,0.68)[2]#binom.test(sum(rt), .N, conf.level = 0.68)$conf.int[2]
                          ), 
                          by = .(rep_name)]

g <- ggplot(summsumm) +
  aes(v, cov, ymin = cov_lo, ymax = cov_up, xmin = v_lo, xmax = v_up, 
      weight = 1 / ((cov_up - cov_lo) + (v_up - v_lo)), label = 1:length(rep_name)) +
  geom_point() +
  geom_errorbar(width = 0.02) +
  geom_errorbarh(height = 0.02) +
  geom_smooth(method = MASS::rlm, formula = y ~ x) + geom_text(size =3, vjust = 1, hjust = 2)+
  labs(x = expression("Instantaneous velocity"~"["*mu*m/s*"]", 
       y = "Proportion of bot on tissue")) +
  theme_light(base_size = 16) 
  
g
```

## . Velocity vs rotational tendency

```{r}
ggplot(summsumm) +
  aes(rt, v, xmin = rt_lo, xmax = rt_up, ymin = v_lo, ymax = v_up, 
      weight = 1 / ((rt_up - rt_lo) + (v_up - v_lo)), label = 1:length(rep_name)) +
  geom_point() +
  geom_errorbar(width = 0.02) +
  geom_errorbarh(height = 0.000002) + geom_text(size =3, vjust = 1, hjust =2)+
  geom_smooth(method = MASS::rlm, formula = y ~ x) +
  labs(x = "Rotational tendency", 
       y = expression("Instantaneous velocity"~"["*mu*m/s*"]")) +
  theme_light(base_size = 16) 
```

## . Rotational tendency vs coverage

```{r}
g <- ggplot(filter(summsumm)) +
  aes(rt, cov, ymin = cov_lo, ymax = cov_up, xmin = rt_lo, xmax = rt_up, 
      weight = 1 / ((rt_up - rt_lo) + (cov_up - cov_lo)), label = 1:length(rep_name)) +
  geom_point() +
  geom_errorbar(width = 0.02) +
  geom_errorbarh(height = 0.02) +
  geom_smooth(method = MASS::rlm, formula = y ~ x) + geom_text(hjust = -1, vjust = 2)+
  xlim(0, 1)+ ylim(0, 1) +
  labs(x = "Rotational tendency", 
       y = "Proportion of bot on tissue") +
  theme_light(base_size = 16) 
g
```

## . Model relationship upper limit of the confidence interval for rotational tendency and coverage

```{r}
m <- lm(cov ~ rt_up1, data = summsumm)
```

```{r}
library(DHARMa)
res <- simulateResiduals(m)
plot(res)
testDispersion(res)
```

```{r}
summary(m)
```

## . Model relationship velocity and coverage

```{r}
m2 <- lm(cov ~ v, data = summsumm)
```

```{r}
library(DHARMa)
res2 <- simulateResiduals(m2)
plot(res2)
testDispersion(res2)
```

```{r}
summary(m2)
```





